version: "3.8"
services:
    libshareclient:
        container_name: libshareclient
        image: smethan/libshareclient:latest
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5001:80"
        restart: always